export default {
  '1': {
    logoURI: '/images/chains/Ethereum.svg',
    name: 'Ethereum Mainnet',
    chainId: 1,
    shortName: 'Ethereum',
    nativeCurrency: { name: 'Ether', symbol: 'ETH', decimals: 18 },
    rpc: ['https://nd-514-058-005.p2pify.com/dc1497bc70edce38d5726b5dad31feb3', 'https://cloudflare-eth.com'],
    explorers: [{ name: 'etherscan', url: 'https://etherscan.io', standard: 'EIP3091' }],
    stableCoins: [
      {
        name: 'USDC',
        symbol: 'USDC',
        address: '0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48',
        decimals: 6,
      },
      {
        name: 'USDT',
        symbol: 'USDT',
        address: '0xdac17f958d2ee523a2206206994597c13d831ec7',
        decimals: 6,
      },
      {
        name: 'BUSD',
        symbol: 'BUSD',
        address: '0x4fabb145d64652a948d72533023f6e7a623c7c53',
        decimals: 18,
      },
      { name: 'DAI', symbol: 'DAI', address: '0x6b175474e89094c44da98b954eedeac495271d0f', decimals: 18 },
    ],
    transportTokens: [
      {
        address: '0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2',
        decimals: 18,
        name: 'Wrapped ETH',
        symbol: 'WETH',
      },
    ],
  },
  '3': {
    logoURI:
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTICicq_7MehApKc-9YaMLf0tACNSveeubKMtqElHVc8EPWaQw1mRMfQVaa3zINe5u-42w&usqp=CAU',
    name: 'Ropsten Test Network',
    chainId: 3,
    shortName: 'Goërli',
    nativeCurrency: { decimals: 0, name: 'Goerli Ether' },
    rpc: [],
    explorers: [{}],
    stableCoins: [],
    transportTokens: [],
  },
  '4': {
    logoURI:
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTICicq_7MehApKc-9YaMLf0tACNSveeubKMtqElHVc8EPWaQw1mRMfQVaa3zINe5u-42w&usqp=CAU',
    name: 'Rinkeby Test Network',
    chainId: 4,
    shortName: 'Rinkeby',
    nativeCurrency: { decimals: 18, name: 'RinkebyETH', symbol: 'ETH' },
    rpc: ['https://rinkeby.infura.io/v3/'],
    explorers: [{ url: 'https://rinkeby.etherscan.io/' }],
    stableCoins: [],
    transportTokens: [],
  },
  '5': {
    logoURI:
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTICicq_7MehApKc-9YaMLf0tACNSveeubKMtqElHVc8EPWaQw1mRMfQVaa3zINe5u-42w&usqp=CAU',
    name: 'Goerli Test Network',
    chainId: 5,
    shortName: 'Goërli',
    nativeCurrency: { name: 'Goerli Ether', symbol: 'ETH', decimals: 18 },
    rpc: ['https://goerli.prylabs.net/'],
    explorers: [{ name: 'etherscan', url: 'https://goerli.etherscan.io', standard: 'EIP3091' }],
    stableCoins: [],
    transportTokens: [],
  },
  '10': {
    logoURI: 'https://cdn-images-1.medium.com/max/1200/1*6zQEwahVQVEPk4QJpKGShw.png',
    name: 'Optimistic Ethereum',
    chainId: 10,
    shortName: 'oeth',
    nativeCurrency: { name: 'Ether', symbol: 'OETH', decimals: 18 },
    rpc: ['https://mainnet.optimism.io/'],
    explorers: [{}],
    stableCoins: [
      {
        name: 'USDC',
        symbol: 'USDC',
        address: '0x7f5c764cbc14f9669b88837ca1490cca17c31607',
        decimals: 6,
      },
      {
        name: 'USDT',
        symbol: 'USDT',
        address: '0x94b008aa00579c1307b0ef2c499ad98a8ce58e58',
        decimals: 6,
      },
      { name: 'DAI', symbol: 'DAI', address: '0xda10009cbd5d07dd0cecc66161fc93d7c9000da1', decimals: 18 },
    ],
    transportTokens: [],
  },
  '14': {
    name: 'Flare Mainnet',
    shortName: 'Harmony',
    chainId: 14,
    chain: 'FLR',
    network: 'flare',
    networkId: 14,
    nativeCurrency: { name: 'Spark', symbol: 'FLR', decimals: 18 },
    rpc: [],
    faucets: [],
    explorers: [],
    infoURL: 'https://flare.xyz',
    logoURI: '/images/chains/harmony.svg',
  },
  '25': {
    name: 'Cronos Mainnet Beta',
    shortName: 'Cronos',
    chain: 'CRO',
    network: 'mainnet',
    rpc: ['https://evm-cronos.crypto.org'],
    faucets: [],
    nativeCurrency: { name: 'Crypto.org Coin', symbol: 'CRO', decimals: 18 },
    infoURL: 'https://cronos.crypto.org',
    logoURI: '/images/chains/cronos.svg',
    chainId: 25,
    networkId: 25,
    explorers: [{ name: 'Cronos Explorer', url: 'https://cronos.crypto.org/explorer', standard: 'none' }],
  },
  '40': {
    name: 'Telos EVM Mainnet',
    chainId: 40,
    shortName: 'Telos EVM',
    chain: 'TLOS',
    network: 'mainnet',
    networkId: 40,
    nativeCurrency: { name: 'Telos', symbol: 'TLOS', decimals: 18 },
    rpc: ['https://mainnet.telos.net/evm'],
    faucets: [],
    explorers: [],
    infoURL: 'https://telos.net',
  },
  '42': { name: 'Kovan Test Network', chainId: 42, chain: 'ETH_TEST', color: '#906afc' },
  '52': {
    logoURI: 'https://oss-us-cdn.maiziqianbao.net/Chain_logo/G61621307040.jpg',
    name: 'CoinEx Smart Chain Mainnet',
    chainId: 52,
    shortName: 'CoinEx',
    nativeCurrency: { name: 'CoinEx Coin', symbol: 'cet', decimals: 18 },
    rpc: [
      'https://rpc.coinex.net',
      'https://rpc1.coinex.net',
      'https://rpc2.coinex.net',
      'https://rpc3.coinex.net',
      'https://rpc4.coinex.net',
    ],
    explorers: [{}],
    stableCoins: [],
    transportTokens: [],
  },
  '56': {
    name: 'Binance Smart Chain Mainnet',
    shortName: 'Binance BSC',
    color: '#dddddd',
    chainId: 56,
    explorerUrl: 'https://bscscan.com/tx/',
    chain: 'BSC',
    network: 'mainnet',
    networkId: 56,
    nativeCurrency: { name: 'Binance Chain Native Token', symbol: 'BNB', decimals: 18 },
    stableCoins: [
      {
        name: 'BUSD',
        symbol: 'BUSD',
        address: '0xe9e7cea3dedca5984780bafc599bd69add087d56',
        decimals: 18,
      },
      {
        name: 'USDC',
        symbol: 'USDC',
        address: '0x8ac76a51cc950d9822d68b83fe1ad97b32cd580d',
        decimals: 6,
      },
      {
        name: 'USDT',
        symbol: 'USDT',
        address: '0x55d398326f99059ff775485246999027b3197955',
        decimals: 6,
      },
      { name: 'DAI', symbol: 'DAI', address: '0x1af3f329e8be154074d8769d1ffa4ee058b1dbc3', decimals: 18 },
    ],
    rpc: [
      'https://bsc-dataseed1.binance.org',
      'https://bsc-dataseed2.binance.org',
      'https://bsc-dataseed3.binance.org',
      'https://bsc-dataseed4.binance.org',
      'https://bsc-dataseed1.defibit.io',
      'https://bsc-dataseed2.defibit.io',
      'https://bsc-dataseed3.defibit.io',
      'https://bsc-dataseed4.defibit.io',
      'https://bsc-dataseed1.ninicoin.io',
      'https://bsc-dataseed2.ninicoin.io',
      'https://bsc-dataseed3.ninicoin.io',
      'https://bsc-dataseed4.ninicoin.io',
      'wss://bsc-ws-node.nariox.org',
    ],
    faucets: [],
    explorers: [{ name: 'bscscan', url: 'https://bscscan.com', standard: 'EIP3091' }],
    infoURL: 'https://www.binance.org',
    logoURI: '/images/chains/binance_smart_chain.svg',
  },
  '61': {
    name: 'Ethereum Classic Mainnet',
    chainId: 61,
    shortName: 'etc',
    chain: 'ETC',
    network: 'mainnet',
    networkId: 1,
    nativeCurrency: { name: 'Ethereum Classic Ether', symbol: 'ETC', decimals: 18 },
    rpc: ['https://ethereumclassic.network'],
    faucets: [],
    explorers: [],
    infoURL: 'https://ethereumclassic.org',
  },
  '66': {
    name: 'OKExChain Mainnet',
    shortName: 'OKExChain',
    chainId: 66,
    chain: 'okexchain',
    network: 'mainnet',
    networkId: 66,
    explorerUrl: 'https://www.oklink.com/okexchain/tx/',
    nativeCurrency: { name: 'OKExChain Global Utility Token', symbol: 'OKT', decimals: 18 },
    stableCoins: [
      {
        name: 'USDC',
        symbol: 'USDC',
        address: '0xc946daf81b08146b1c7a8da2a851ddf2b3eaaf85',
        decimals: 6,
      },
      {
        name: 'USDT',
        symbol: 'USDT',
        address: '0x382bb369d343125bfb2117af9c149795c6c65c50',
        decimals: 6,
      },
      { name: 'BUSD', symbol: 'BUSD', address: '0x332730a4f6e03d9c55829435f10360e13cfa41ff', decimals: 18 },
    ],
    rpc: ['https://exchainrpc.okex.org'],
    faucets: [],
    explorers: [{ name: 'OKLink', url: 'https://www.oklink.com/okexchain', standard: 'EIP3091' }],
    infoURL: 'https://www.okex.com/okexchain',
    logoURI: '/images/chains/okex.png',
  },
  '77': {
    name: 'POA Network Sokol',
    chainId: 77,
    shortName: 'poa',
    chain: 'POA',
    network: 'sokol',
    networkId: 77,
    nativeCurrency: { name: 'POA Sokol Ether', symbol: 'POA', decimals: 18 },
    rpc: ['https://sokol.poa.network', 'wss://sokol.poa.network/wss', 'ws://sokol.poa.network:8546'],
    faucets: ['https://faucet-sokol.herokuapp.com'],
    explorers: [],
    infoURL: 'https://poa.network',
  },
  '100': {
    logoURI: '/images/chains/xdai.svg',
    name: 'xDAI Chain',
    chainId: 100,
    shortName: 'xDAI',
    nativeCurrency: { name: 'xDAI', symbol: 'xDAI', decimals: 18 },
    rpc: [
      'https://rpc.xdaichain.com',
      'https://xdai.poanetwork.dev',
      'wss://rpc.xdaichain.com/wss',
      'wss://xdai.poanetwork.dev/wss',
      'http://xdai.poanetwork.dev',
      'https://dai.poa.network',
      'ws://xdai.poanetwork.dev:8546',
    ],
    explorers: [{ name: 'Gnosis Scan', url: 'https://gnosisscan.io' }],
    stableCoins: [
      {
        name: 'USDC',
        symbol: 'USDC',
        address: '0xddafbb505ad214d7b80b1f830fccc89b60fb7a83',
        decimals: 6,
      },
      {
        name: 'USDT',
        symbol: 'USDT',
        address: '0x4ECaBa5870353805a9F068101A40E0f32ed605C6',
        decimals: 6,
      },
      { name: 'DAI', symbol: 'DAI', address: '0x44fA8E6f47987339850636F88629646662444217', decimals: 18 },
    ],
    transportTokens: [],
  },
  '106': {
    name: 'Velas',
    shortName: 'Velas',
    chain: 'Velas',
    network: 'mainnet',
    rpc: ['https://evmexplorer.velas.com/rpc', 'https://explorer.velas.com/rpc'],
    faucets: [],
    nativeCurrency: { name: 'Velas', symbol: 'VLX', decimals: 18 },
    infoURL: 'https://velas.com',
    chainId: 106,
    networkId: 106,
    explorers: [{ name: 'Velas Explorer', url: 'https://evmexplorer.velas.com', standard: 'EIP3091' }],
    logoURI: '/images/chains/velas.png',
  },
  '108': {
    name: 'ThunderCore Mainnet',
    chainId: 108,
    shortName: 'TT',
    chain: 'TT',
    network: 'mainnet',
    networkId: 108,
    nativeCurrency: { name: 'ThunderCore Mainnet Ether', symbol: 'TT', decimals: 18 },
    rpc: ['https://mainnet-rpc.thundercore.com'],
    faucets: ['https://faucet.thundercore.com'],
    explorers: [],
    infoURL: 'https://thundercore.com',
  },
  '111': {
    name: 'EtherLite Chain',
    chainId: 111,
    shortName: 'ETL',
    chain: 'ETL',
    network: 'mainnet',
    networkId: 111,
    nativeCurrency: { name: 'EtherLite', symbol: 'ETL', decimals: 18 },
    rpc: ['https://rpc.etherlite.org'],
    faucets: ['https://etherlite.org/faucets'],
    explorers: [],
    infoURL: 'https://etherlite.org',
  },
  '128': {
    name: 'Huobi ECO Chain Mainnet',
    shortName: 'Huobi ECO',
    chainId: 128,
    explorerUrl: 'https://hecoinfo.com/tx/',
    chain: 'Heco',
    network: 'mainnet',
    networkId: 128,
    nativeCurrency: { name: 'Huobi ECO Chain Native Token', symbol: 'HT', decimals: 18 },
    stableCoins: [
      {
        name: 'USDT',
        symbol: 'USDT',
        address: '0xa71edc38d189767582c38a3145b5873052c3e47a',
        decimals: 6,
      },
    ],
    rpc: ['https://http-mainnet.hecochain.com', 'wss://ws-mainnet.hecochain.com'],
    faucets: [],
    explorers: [],
    infoURL: 'https://hecoinfo.com',
    logoURI: '/images/chains/heco.png',
  },
  '137': {
    name: 'Matic Mainnet',
    shortName: 'Polygon',
    chainId: 137,
    explorerUrl: 'https://polygonscan.com/tx/',
    chain: 'Matic',
    network: 'mainnet',
    networkId: 137,
    nativeCurrency: { name: 'Matic', symbol: 'MATIC', decimals: 18 },
    stableCoins: [
      {
        name: 'USDC',
        symbol: 'USDC',
        address: '0x2791bca1f2de4661ed88a30c99a7a9449aa84174',
        decimals: 6,
      },
      {
        name: 'USDT',
        symbol: 'USDT',
        address: '0xc2132d05d31c914a87c6611c10748aeb04b58e8f',
        decimals: 6,
      },
      {
        name: 'BUSD',
        symbol: 'BUSD',
        address: '0x9fb83c0635de2e815fd1c21b3a292277540c2e8d',
        decimals: 18,
      },
      { name: 'DAI', symbol: 'DAI', address: '0x8f3cf7ad23cd3cadbd9735aff958023239c6a063', decimals: 18 },
    ],
    rpc: ['https://rpc-mainnet.matic.network', 'wss://ws-mainnet.matic.network'],
    faucets: [],
    explorers: [{ name: 'polygonscan', url: 'https://polygonscan.com', standard: 'EIP3091' }],
    infoURL: 'https://matic.network/',
    logoURI: '/images/chains/polygon.svg',
  },
  '250': {
    name: 'Fantom Opera',
    shortName: 'Fantom Opera',
    chainId: 250,
    chain: 'FTM',
    network: 'mainnet',
    networkId: 250,
    explorerUrl: 'https://ftmscan.com/tx/',
    nativeCurrency: { name: 'Fantom', symbol: 'FTM', decimals: 18 },
    stableCoins: [
      {
        name: 'USDC',
        symbol: 'USDC',
        address: '0x04068da6c83afcfa0e13ba15a6696662335d5b75',
        decimals: 6,
      },
      {
        name: 'USDT',
        symbol: 'USDT',
        address: '0x049d68029688eabf473097a2fc38ef61633a3c7a',
        decimals: 6,
      },
      { name: 'DAI', symbol: 'DAI', address: '0x8D11eC38a3EB5E956B052f67Da8Bdc9bef8Abf3E', decimals: 18 },
    ],
    rpc: ['https://rpcapi.fantom.network'],
    faucets: [],
    explorers: [{ name: 'ftmscan', url: 'https://ftmscan.com', standard: 'EIP3091' }],
    infoURL: 'https://fantom.foundation',
    logoURI: '/images/chains/fantom.svg',
  },
  '288': {
    name: 'Boba',
    shortName: 'Boba',
    chain: 'ETH',
    network: 'mainnet',
    rpc: ['https://mainnet.boba.network/'],
    faucets: [],
    nativeCurrency: { name: 'Ether', symbol: 'ETH', decimals: 18 },
    infoURL: 'https://boba.network',
    chainId: 288,
    networkId: 288,
    explorers: [{ name: 'Blockscout', url: 'https://blockexplorer.boba.network/', standard: 'none' }],
    logoURI: '/images/chains/boba.svg',
  },
  '321': {
    name: 'KuCoin Community Chain Mainnet',
    shortName: 'KuCoin Chain',
    chainId: 321,
    chain: 'KCC',
    network: 'mainnet',
    networkId: 321,
    explorerUrl: 'https://explorer.kcc.io/tx/',
    nativeCurrency: { name: 'KuCoin Token', symbol: 'KCS', decimals: 18 },
    stableCoins: [
      {
        name: 'USDC',
        symbol: 'USDC',
        address: '0x980a5afef3d17ad98635f6c5aebcbaeded3c3430',
        decimals: 6,
      },
      { name: 'USDT', symbol: 'USDT', address: '0x0039f574ee5cc39bdd162e9a88e3eb1f111baf48', decimals: 6 },
    ],
    rpc: ['https://rpc-mainnet.kcc.network', 'wss://rpc-ws-mainnet.kcc.network'],
    faucets: [],
    explorers: [{ name: 'KCC Explorer', url: 'https://explorer.kcc.io/en', standard: 'EIP3091' }],
    infoURL: 'https://kcc.io',
    logoURI: '/images/chains/KuCoin.svg',
  },
  '888': {
    name: 'Wanchain',
    chainId: 888,
    shortName: 'wan',
    chain: 'WAN',
    network: 'mainnet',
    networkId: 888,
    nativeCurrency: { name: 'Wancoin', symbol: 'WAN', decimals: 18 },
    rpc: ['https://gwan-ssl.wandevs.org:56891/'],
    faucets: [],
    explorers: [],
    infoURL: 'https://www.wanscan.org',
  },
  '1088': {
    name: 'Metis',
    shortName: 'Metis',
    chain: 'METIS',
    network: 'mainnet',
    rpc: ['https://andromeda.metis.io/?owner=1088'],
    faucets: [],
    nativeCurrency: { name: 'Metis', symbol: 'METIS', decimals: 18 },
    infoURL: 'https://www.metis.io',
    chainId: 1088,
    networkId: 1088,
    explorers: [{ name: 'blockscout', url: 'https://andromeda-explorer.metis.io/', standard: 'EIP3091' }],
    logoURI: '/images/chains/metis.png',
  },
  '1139': {
    name: 'MathChain',
    chainId: 1139,
    shortName: 'MATH',
    chain: 'MATH',
    network: 'mainnet',
    networkId: 1139,
    nativeCurrency: { name: 'MathChain', symbol: 'MATH', decimals: 18 },
    rpc: [],
    faucets: [],
    explorers: [],
    infoURL: 'https://mathchain.org',
  },
  '1284': {
    name: 'Moonbeam Polkadot',
    chainId: 1284,
    shortName: 'mbeam',
    chain: 'MOON',
    network: 'moonbeam',
    networkId: 1284,
    nativeCurrency: { name: 'Glimmer', symbol: 'GLMR', decimals: 18 },
    rpc: [],
    faucets: [],
    explorers: [],
    infoURL: 'https://moonbeam.network/networks/moonbeam/',
  },
  '1285': {
    name: 'Moonriver Kusama',
    chainId: 1285,
    shortName: 'mriver',
    chain: 'MOON',
    network: 'moonriver',
    networkId: 1285,
    nativeCurrency: { name: 'River', symbol: 'RIVER', decimals: 18 },
    rpc: [],
    faucets: [],
    explorers: [],
    infoURL: 'https://moonbeam.network/networks/moonriver/',
  },
  '1286': {
    name: 'Moonrock Rococo',
    chainId: 1286,
    shortName: 'mrock',
    chain: 'MOON',
    network: 'moonrock',
    networkId: 1286,
    nativeCurrency: { name: 'Rocs', symbol: 'ROC', decimals: 18 },
    rpc: [],
    faucets: [],
    explorers: [],
    infoURL: '',
  },
  '1287': {
    name: 'Moonbeam Testnet Moonbase Alpha',
    chainId: 1287,
    shortName: 'mbase',
    chain: 'MOON',
    network: 'moonbase',
    networkId: 1287,
    nativeCurrency: { name: 'Dev', symbol: 'DEV', decimals: 18 },
    rpc: ['https://rpc.testnet.moonbeam.network', 'wss://wss.testnet.moonbeam.network'],
    faucets: [],
    explorers: [],
    infoURL: 'https://docs.moonbeam.network/networks/testnet/',
  },
  '2000': {
    logoURI: 'https://docs.dogechain.dog/img/logo.png',
    name: 'DogeChain',
    chainId: 2000,
    shortName: 'DogeChain',
    nativeCurrency: { name: 'Wrapped Dogecoin', symbol: 'wDOGE', decimals: 18 },
    rpc: ['https://rpc-us.dogechain.dog', 'https://rpc.dogechain.dog', 'https://rpc-sg.dogechain.dog'],
    explorers: [{ url: 'https://explorer.dogechain.dog' }],
    stableCoins: [
      {
        address: '0x765277EebeCA2e31912C9946eAe1021199B39C61',
        decimals: 6,
        name: 'USDC',
        symbol: 'USDC',
      },
      {
        address: '0xE3F5a90F9cb311505cd691a46596599aA1A0AD7D',
        decimals: 6,
        name: 'USDT',
        symbol: 'USDT',
      },
      { address: '0x639A647fbe20b6c8ac19E48E2de44ea792c62c5C', decimals: 18, name: 'Dai', symbol: 'DAI' },
    ],
    transportTokens: [],
  },
  '4689': {
    name: 'IoTeX',
    shortName: 'IoTeX',
    chain: 'iotex.io',
    network: 'mainnet',
    rpc: ['https://babel-api.mainnet.iotex.io'],
    faucets: [],
    nativeCurrency: { name: 'IoTeX', symbol: 'IOTX', decimals: 18 },
    infoURL: 'https://iotex.io',
    chainId: 4689,
    networkId: 4689,
    explorers: [{ name: 'iotexscan', url: 'https://iotexscan.io', standard: 'EIP3091' }],
    logoURI: '/images/chains/iotex.png',
  },
  '32659': {
    name: 'Fusion Mainnet',
    chainId: 32659,
    shortName: 'fsn',
    chain: 'FSN',
    network: 'mainnet',
    networkId: 32659,
    nativeCurrency: { name: 'Fusion', symbol: 'FSN', decimals: 18 },
    rpc: ['https://mainnet.anyswap.exchange', 'https://fsn.dev/api'],
    faucets: [],
    explorers: [],
    infoURL: 'https://www.fusion.org/',
  },
  '42161': {
    name: 'Arbitrum One',
    shortName: 'Arbitrum',
    chainId: 42161,
    chain: 'ARETH',
    network: 'mainnet',
    networkId: 42161,
    explorerUrl: 'https://arbiscan.io/tx/',
    nativeCurrency: { name: 'Arbitrum One', symbol: 'ARETH', decimals: 18 },
    stableCoins: [
      {
        name: 'USDC',
        symbol: 'USDC',
        address: '0xff970a61a04b1ca14834a43f5de4533ebddb5cc8',
        decimals: 6,
      },
      {
        name: 'USDT',
        symbol: 'USDT',
        address: '0xfd086bc7cd5c481dcc9c85ebe478a1c0b69fcbb9',
        decimals: 6,
      },
      { name: 'DAI', symbol: 'DAI', address: '0xda10009cbd5d07dd0cecc66161fc93d7c9000da1', decimals: 18 },
    ],
    rpc: ['https://arb1.arbitrum.io/rpc'],
    faucets: [],
    explorers: [],
    infoURL: 'https://arbitrum.io',
    logoURI: '/images/chains/Arbitrum.svg',
  },
  '42220': {
    name: 'Celo Mainnet',
    shortName: 'Celo',
    chainId: 42220,
    chain: 'CELO',
    network: 'Mainnet',
    networkId: 42220,
    nativeCurrency: { name: 'CELO', symbol: 'CELO', decimals: 18 },
    rpc: ['https://forno.celo.org', 'wss://forno.celo.org/ws'],
    faucets: [],
    explorerUrl: 'https://explorer.celo.org/tx/',
    infoURL: 'https://docs.celo.org/',
    logoURI: '/images/chains/celo.svg',
  },
  '43114': {
    logoURI: '/images/chains/avalanche.png',
    name: 'Avalanche Mainnet',
    chainId: 43114,
    shortName: 'Avalanche',
    nativeCurrency: { name: 'Avalanche', symbol: 'AVAX', decimals: 18 },
    rpc: [
      'https://api.avax.network/ext/bc/C/rpc',
      'https://rpc.ankr.com/avalanche',
      'https://1rpc.io/avax/c',
      'https://ava-mainnet.public.blastapi.io/ext/bc/C/rpc',
      'https://avalancheapi.terminet.io/ext/bc/C/rpc',
    ],
    explorers: [{}],
    stableCoins: [
      {
        name: 'USDC',
        symbol: 'USDC',
        address: '0xa7d7079b0fead91f3e65f86e8915cb59c1a4c664',
        decimals: 6,
      },
      {
        name: 'USDT',
        symbol: 'USDT',
        address: '0xc7198437980c041c805a1edcba50c1ce5db95118',
        decimals: 6,
      },
      {
        name: 'BUSD',
        symbol: 'BUSD',
        address: '0x19860ccb0a68fd4213ab9d8266f7bbf05a8dde98',
        decimals: 18,
      },
      { name: 'DAI', symbol: 'DAI', address: '0xd586e7f844cea2f87f50152665bcbc2c279d8d70', decimals: 18 },
    ],
    transportTokens: [],
  },
  '1313161554': {
    name: 'Aurora',
    shortName: 'Aurora',
    chain: 'NEAR',
    network: 'mainnet',
    rpc: ['https://mainnet.aurora.dev'],
    faucets: [],
    nativeCurrency: { name: 'Ether', symbol: 'aETH', decimals: 18 },
    infoURL: 'https://aurora.dev',
    chainId: 1313161554,
    networkId: 1313161554,
    logoURI: '/images/chains/aurora.png',
  },
  '1666600000': {
    logoURI: 'https://get.celer.app/cbridge-icons/chain-icon/Harmony.png',
    name: 'Harmony ONE',
    chainId: 1666600000,
    shortName: 'harmony',
    nativeCurrency: { name: 'Harmony ONE', symbol: 'ONE', decimals: 18 },
    rpc: ['https://api.harmony.one'],
    explorers: [{}],
    stableCoins: [
      {
        name: 'USDC',
        symbol: 'USDC',
        address: '0x985458e523db3d53125813ed68c274899e9dfab4',
        decimals: 6,
      },
      {
        name: 'USDT',
        symbol: 'USDT',
        address: '0x3c2b8be99c50593081eaa2a724f0b8285f5aba8f',
        decimals: 6,
      },
      {
        name: 'BUSD',
        symbol: 'BUSD',
        address: '0xe176ebe47d621b984a73036b9da5d834411ef734',
        decimals: 18,
      },
      { name: 'DAI', symbol: 'DAI', address: '0xef977d2f931c1978db5f6747666fa1eacb0d0339', decimals: 18 },
    ],
    transportTokens: [],
  },
} as any;
